version: '3'
services:
  shell:
    build: .
    ports:
      - 5001:10001
    read_only: true
    cap_drop:
      - all
              
    restart: on-failure

    deploy:
        resources:
            limits:
              cpus: '0.2'
              memory: 1000M